sudo: required
dist: trusty

services:
  - docker

language: java
jdk:
  - openjdk8
    #  - oraclejdk8

git:
  submodules: false
before_install:
  - docker pull aaron1011/xvfb-docker
  - docker run -d -v /tmp/.X11-unix:/tmp/.X11-unix aaron1011/xvfb-docker
  #- sudo add-apt-repository ppa:techsavvy8989/trusty-backport
  #- sudo apt-get update
  #- sudo wget "https://dl.bintray.com/aaron1011/McTester/Xvfb" -O /usr/bin/Xvfb 
  - scripts/travis-initialize-submodules

install: ./gradlew setupDecompWorkspace
script: DISPLAY=:99 ./gradlew test --stacktrace
after_failure: scripts/upload

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
