sudo: required
dist: trusty

services:
  - docker

language: java
jdk:
  - openjdk8
  - oraclejdk8

git:
  submodules: false
before_install:
  - scripts/run-xvfb
  - scripts/travis-initialize-submodules

install: ./gradlew setupDecompWorkspace
script: DISPLAY=:99 ./gradlew test --stacktrace
after_failure: scripts/upload

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/.gradle/
    - $TRAVIS_BUILD_DIR/build/


env:
  global:
    - MCTESTER_UPLOAD_URL="https://openwhisk.ng.bluemix.net/api/v1/web/aa1ronham%40gmail.com_dev/default/image-upload.json"
  matrix:
    - BUILD_NUM=0
    - BUILD_NUM=1
    - BUILD_NUM=2
    - BUILD_NUM=3
    - BUILD_NUM=4
    - BUILD_NUM=5
    - BUILD_NUM=6
    - BUILD_NUM=7
    - BUILD_NUM=8
    - BUILD_NUM=9
    - BUILD_NUM=10
    - BUILD_NUM=11
    - BUILD_NUM=12
    - BUILD_NUM=13
    - BUILD_NUM=14
    - BUILD_NUM=15
