sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
    #  - oraclejdk8

git:
  submodules: false
before_install: scripts/travis-initialize-submodules

install: ./gradlew setupDecompWorkspace
script: xvfb-run ./gradlew test
after_failure: scripts/upload

notifications:
  email: false
